"""add suppliers manufacturers stock_locations build_orders

Revision ID: 092e381e9886
Revises: ae89bc3ee4b7
Create Date: 2026-03-21 01:18:24.718056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092e381e9886'
down_revision: Union[str, Sequence[str], None] = 'ae89bc3ee4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
