"""add supplier_part_number to feeders

Revision ID: 099386666730
Revises: ba00f398513a
Create Date: 2026-03-26 01:06:17.481740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099386666730'
down_revision: Union[str, Sequence[str], None] = 'ba00f398513a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_part_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeders', schema=None) as batch_op:
        batch_op.drop_column('supplier_part_number')

    # ### end Alembic commands ###
