"""add invoice item fields for inventory import

Revision ID: 67a1e3052c22
Revises: 4d15fd1a16a2
Create Date: 2026-03-29 21:43:51.778648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a1e3052c22'
down_revision: Union[str, Sequence[str], None] = '4d15fd1a16a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_to_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suggested_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('suggested_package', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supplier_part_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('supplier_part_number')
        batch_op.drop_column('suggested_package')
        batch_op.drop_column('suggested_category')
        batch_op.drop_column('added_to_stock')

    op.create_table('saved_labels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('paper_size', sa.VARCHAR(length=20), nullable=False),
    sa.Column('template_index', sa.INTEGER(), nullable=False),
    sa.Column('font_size', sa.INTEGER(), nullable=False),
    sa.Column('font_weight', sa.VARCHAR(length=10), nullable=False),
    sa.Column('show_border', sa.BOOLEAN(), nullable=False),
    sa.Column('labels_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
