"""add categories footprints parameters attachments part_lots

Revision ID: 6a95c288e46f
Revises: 092e381e9886
Create Date: 2026-03-21 02:09:51.872757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a95c288e46f'
down_revision: Union[str, Sequence[str], None] = '092e381e9886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('footprint_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ipn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_order_quantity', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_components_category_id', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_components_footprint_id', 'footprints', ['footprint_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('min_order_quantity')
        batch_op.drop_column('status')
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('ipn')
        batch_op.drop_column('mpn')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('tags')
        batch_op.drop_column('footprint_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
